### ISSUE TITLE
[Bug]: Not enough mana allotted so account ended up with negative BIC [Nova]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/iota-sdk#2230] opened 2024-04-18 15:00 UTC
### Issue description

I just experienced an account going to negative BIC because the allotment was a tiny bit below the block cost. see block `0x44f53080acc7f9470a9cb863b7521f168552832ed72ed63f32b29c76abab217929040200` 
I understand this shouldnt happen because we always prepare everything again right before sending and we aim for block cost = mana allotment so the BIC is always 0 for common wallets

### Version

`57a898984c6ab1ba06929b2b94ea7bc08bb1b694`

### Expected behaviour

Account with BIC 0 after every block

### Actual behaviour

Suddenly ended up with -0.0005Mana because the block cost was 0.0005 more expensive than it was alloted

### Can the issue reliably be reproduced?

No

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment] 2024-04-18 15:46
Haven't verified it yet, but seems like this is caused by the burning of outputs, here is a failing test
```Rust
#[tokio::test]
async fn burn_nft_check_mana() {
    let secret_manager = SecretManager::try_from_mnemonic(Client::generate_mnemonic().unwrap()).unwrap();

    let ed25519_address = secret_manager
        .generate_ed25519_addresses(GetAddressesOptions::default().with_range(0..1))
        .await
        .unwrap()[0]
        .clone()
        .into_inner();

    let protocol_parameters = iota_mainnet_protocol_parameters().clone();
    let account_id_1 = AccountId::from_str(ACCOUNT_ID_1).unwrap();
    let nft_id_1 = NftId::from_str(NFT_ID_1).unwrap();
    let reference_mana_cost = 1;

    let inputs = build_inputs(
        [(
            Nft {
                amount: 1_000_000,
                mana: 1_000_000,
                nft_id: nft_id_1,
                address: ed25519_address.clone(),
                sender: None,
                issuer: None,
                sdruc: None,
                expiration: None,
            },
            Some(Bip44::new(SHIMMER_COIN_TYPE)),
        )],
        Some(SLOT_INDEX),
    );
    let outputs = build_outputs([]);

    let selected = TransactionBuilder::new(
        inputs.clone(),
        outputs.clone(),
        [ed25519_address],
        SLOT_INDEX,
        SLOT_COMMITMENT_ID,
        protocol_parameters.clone(),
    )
    .with_burn(Burn::new().set_nfts(HashSet::from([nft_id_1])))
    .with_min_mana_allotment(account_id_1, reference_mana_cost)
    .finish()
    .unwrap();

    assert_eq!(
        selected.transaction.capabilities(),
        &TransactionCapabilities::from([TransactionCapabilityFlag::DestroyNftOutputs])
    );
    assert!(unsorted_eq(&selected.inputs_data, &inputs));

    let inputs = selected
        .inputs_data
        .iter()
        .map(|input| (input.output_id(), &input.output))
        .collect::<Vec<_>>();

    iota_sdk::types::block::semantic::SemanticValidationContext::new(
        &selected.transaction,
        &inputs,
        None,
        None,
        &protocol_parameters,
    )
    .validate()
    .unwrap();

    assert_eq!(selected.transaction.outputs().len(), 1);

    let unlocks = secret_manager
        .transaction_unlocks(&selected, &protocol_parameters)
        .await
        .unwrap();

    let signed_transaction_payload = SignedTransactionPayload::new(selected.transaction.clone(), unlocks).unwrap();

    let basic_block_body = BlockBody::build_basic(
        StrongParents::from_vec(vec![BlockId::new([0; 36])]).unwrap(),
        (protocol_parameters.work_score_parameters(), reference_mana_cost),
    )
    .with_payload(Payload::from(signed_transaction_payload))
    .finish()
    .unwrap();

    assert_eq!(selected.transaction.allotments().len(), 1);
    assert_eq!(
        selected.transaction.allotments().first().unwrap().mana(),
        basic_block_body.max_burned_mana(),
    );
}
```

**Comment by thibault-martinez** [comment] 2024-04-19 10:34
Fixed by https://github.com/iotaledger/iota-sdk/pull/2231

**Closed as completed by thibault-martinez** 2024-04-19 10:34 UTC
