### ISSUE TITLE
[Bug]: python iota-sdk arm package

### ISSUE THREAD

**Issue by tangletips** [iotaledger/iota-sdk#1484] opened 2023-10-21 23:36 UTC
### Issue description

When the server is ARM 
`pip install iota-sdk`
installs the old 0.1.0 version, which seems to be the only version for ARM.
the command
`pip install --verbose  --log test.log  iota-sdk
`
shows all packages with the info:

```
...
2023-10-21T23:09:48,860   Skipping link: none of the wheel's tags (cp39-cp39-manylinux_2_35_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/99/44/c9a8c0e6a3fe3067fbd921489bc35f61e683c00dd064c5feb24818b8c847/iota_sdk-1.1.0-cp39-cp39-manylinux_2_35_x86_64.whl#sha256=fde75348cffb34a53eeb8970f1ac156c8f7cf12a29772054ad2f03be39d90c16 (from https://pypi.org/simple/iota-sdk/)
2023-10-21T23:09:48,861   Skipping link: none of the wheel's tags (cp39-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/e0/f9/06b271d9308151546345379581fe1f941e10ab306ed4f23f363e235c92fb/iota_sdk-1.1.0-cp39-none-win_amd64.whl#sha256=68b5ef7c888d1a4114b98cf7e679a96e6d6f6b21d98a4c027a21c54f8b855f03 (from https://pypi.org/simple/iota-sdk/)
2023-10-21T23:09:48,861 Skipping link: not a file: https://pypi.org/simple/iota-sdk/
2023-10-21T23:09:48,861 Given no hashes to check 1 links for project 'iota-sdk': discarding no candidates
```

### Version

Linux ubuntu-8gb-fsn1-1 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:34:05 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
Python 3.10.12

### Expected behaviour

installation of latest iota-sdk, which is 1.1.0

### Actual behaviour

on arm machine 
installation of 0.1.0

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. login to a arm linux
2. pip install iota-sdk

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment] 2024-01-11 15:47
Duplicate of https://github.com/iotaledger/iota-sdk/issues/1161.

**Closed as completed by thibault-martinez** 2024-01-11 15:47 UTC
Labels: b-python, i-release, t-investigate
