### ISSUE TITLE
Add an example of destroying a foundry when account owns all tokens

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#524] opened 2023-06-01 13:36 UTC
## Description

If an account has a foundry, and the foundry owns all tokens it made, we should be able to destroy the foundry

## Motivation

UX

## Requirements

1. find tokens created
2. check if we control all
3. Melt tokens
4. Destroy foundry

## Open questions (optional)

This could be overkill, or maybe split it up in 2?
Do we want to add it to the bindings then though?

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by Thoralf-M** [comment] 2023-06-01 21:41
> Burn tokens
> Destroy foundry

If you burn them it will not work :trollface: Only melting (with decrease_native_token_supply) does
Also we don't want methods to create two transactions, because that doesn't work with prepared data signing and single tx id return type and for this thing we would also need syncing in between after first tx got confirmed

But in the cli wallet it could be done with a single command

**Comment by thibault-martinez** [comment] 2023-08-30 08:32
Closed by https://github.com/iotaledger/iota-sdk/pull/1087

**Closed as completed by thibault-martinez** 2023-08-30 08:32 UTC
