### ISSUE TITLE
[Bug]: Migration from chrysalis to stardust sometimes leads to zero accounts

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/iota-sdk#1467] opened 2023-10-19 12:27 UTC
### Issue description

We have some users unable to enter their profiles because the profiles have zero accounts after the network upgrade. The sdk debug logs were shared to @thibault-martinez and @Thoralf-M to help discovering the issue

Please note that we can provide a fix on firefly, this is not a blocker to fix a production version of the firefly wallet

### Version

1.1.0

### Expected behaviour

Profiles with already existing accounts before the merge should keep these existing acconts after the migration

### Actual behaviour

Some users are left with no accounts after the upgrade

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

We havent found a way to reproduce this sorry

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment] 2024-01-26 10:36
Closing this since we have no reproduction steps, couldn't find the reason and got no other reports of this happening. If it happens, one can use `recover_accounts()` to find the accounts again if they had funds, or create the accounts manually with `create_account()`. `wallet.get_chrysalis_data()` could also help to see what accounts and addresses previously existed.

**Closed as completed by Thoralf-M** 2024-01-26 10:36 UTC
Labels: bug, m-wallet, t-investigate
