### ISSUE TITLE
[Bug]: Update relative import path in the nodejs bindings

### ISSUE THREAD

**Issue by brancoder** [iotaledger/iota-sdk#819] opened 2023-07-19 14:02 UTC
### Issue description

Importing enums needs to be done in this way:
`import { WalletEventType } from '@iota/wallet/out/types'`
because relative import from the line below is not correct anymore:

https://github.com/iotaledger/iota-sdk/blob/e6253342cd5d4571bb7c0c3775d4396d329dfcc5/bindings/nodejs-old/lib/bindings.ts#L8

https://github.com/iotaledger/firefly/pull/6966#issuecomment-1642116787

### Version

rc.40 and new nodejs SDK bindings

### Expected behaviour

import enums from iota/wallet:
`import { WalletEventType } from '@iota/wallet'`

### Actual behaviour

import { WalletEventType } from '@iota/wallet/out/types'

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment] 2023-07-20 08:41
I don't see how this is related to the index.node import, the enum is defined on the TS/JS side
Also in nodejs this works fine for me
```
const { WalletEventType } = require('@iota/wallet')

const r = WalletEventType.ConsolidationRequired
console.log(r)
```

**Comment by Tuditi** [comment] 2023-07-20 09:05
I think the issue is related to webpack not being able to load the native module correctly into svelte files. I can double check this, but what Branco wrote, is definitely a problem we have been having for a while in Firefly. We always patched it by importing from `@iota/wallet/out/types`.

**Comment by Thoralf-M** [comment] 2023-08-15 10:00
@Tuditi since this is related to webpack in Firefly and not an issue with the library itself we can close this now? One part where the index.node was imported in the types was changed in https://github.com/iotaledger/iota-sdk/commit/ade97497f554f9ea22b8c4abc9a47237873cf46d, so this should make it possible to only import types without the binary

**Comment by Tuditi** [comment] 2023-08-16 07:39
That's good! You can close this issue, since the description isn't correct. The types are still difficult to use with webpack, so it would be nice for your users if they could find documentation about the usage somewhere. The fix is to import types from `@iota/sdk/out/types` instead of `@iota/sdk`.

Maybe there is another solution on our end, but I don't know it.

**Closed as completed** 2023-08-16 07:40 UTC
Labels: b-nodejs
